### ISSUE TITLE
Update Page button works only once

### ISSUE THREAD

**Issue by jphms** [whitecube/nova-page#35]
Not sure if issue or if this is the intended functionality, but once you update a page it doesn't redirect you to the details page as usual nova resources do.
But more importantly, if you update the page once, but then change some values and hit the update again you are greeted with 

> "Another user has updated this resource since this page was loaded. Please refresh the page and try again."

Using laravel 5.8.17 and latest nova 2.0.5.

**Comment by voidgraphics** [comment]
Thanks for the heads up, we will get this fixed by the end of next week.

**Comment by voidgraphics** [comment]
Hi @jphms, I have seen the same issue before but now I can't seem to replicate it anymore.

I don't think any of the other fixes I have made today could have had the side effect to fix this, so I'm pretty confused. I think it may only happen on pages that contain certain fields.

Does it happen on every page registered in your application? Can you try a page that only contains a text field and see if it happens there as well?

Thanks

**Comment by jphms** [comment]
Hey @voidgraphics, I just tried and yes, it happens on every page, tried one page with just a text field and the same behaviour happened. Then I ran a composer update, and still the same issue persists (though it didn't update this package).

**Comment by voidgraphics** [comment]
Which version of nova-page are you using?

Can you try changing to `dev-master` and see if it still happens?

**Comment by voidgraphics** [comment]
Fixed, it will be included in the next release, which is coming soon.
